class _BotCommands:
    def __init__(self):
        self.StartCommand = 'india'
        self.MirrorCommand = 'talibaan'
        self.UnzipMirrorCommand = 'america'
        self.TarMirrorCommand = 'russia'
        self.ZipMirrorCommand = 'srilanka'
        self.CancelMirror = 'bangladesh'
        self.CancelAllCommand = 'china'
        self.ListCommand = 'find'
        self.StatusCommand = 'tokyo'
        self.AuthorizedUsersCommand = 'japan'
        self.AuthorizeCommand = 'canada'
        self.UnAuthorizeCommand = 'peninsula'
        self.AddSudoCommand = 'denmark'
        self.RmSudoCommand = 'london'
        self.PingCommand = 'paris'
        self.RestartCommand = 'newyork'
        self.StatsCommand = 'netherland'
        self.HelpCommand = 'afghanistaan'
        self.LogCommand = 'log'
        self.SpeedCommand = 'pakistaan'
        self.CloneCommand = 'copy'
        self.CountCommand = 'scottland'
        self.WatchCommand = 'berlin'
        self.TarWatchCommand = 'helsinki'
        self.DeleteCommand = 'denver'
        self.ShellCommand = 'africa'
        self.ExecHelpCommand = 'losangeles'
        self.TsHelpCommand = 'dubai'

BotCommands = _BotCommands()
